// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     alertrule.avsc
 */

package alertrule

import (
	"io"
)

type AlertRule struct {
	DomainID     string
	Service      string
	Operation    string
	Env          string
	Duration     int64
	Measure      string
	Submeasure   string
	Limit        float64
	Upper        bool
	CreationTime int64
	Type         string
	Function     string
	Disabled     bool
}

func DeserializeAlertRule(r io.Reader) (*AlertRule, error) {
	return readAlertRule(r)
}

func NewAlertRule() *AlertRule {
	v := &AlertRule{}
	v.Env = "none"

	return v
}

func (r *AlertRule) Schema() string {
	return "{\"fields\":[{\"name\":\"DomainID\",\"type\":\"string\"},{\"name\":\"Service\",\"type\":\"string\"},{\"name\":\"Operation\",\"type\":\"string\"},{\"default\":\"none\",\"name\":\"Env\",\"type\":\"string\"},{\"name\":\"Duration\",\"type\":\"long\"},{\"name\":\"Measure\",\"type\":\"string\"},{\"name\":\"Submeasure\",\"type\":\"string\"},{\"name\":\"Limit\",\"type\":\"double\"},{\"name\":\"Upper\",\"type\":\"boolean\"},{\"name\":\"CreationTime\",\"type\":\"long\"},{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"Function\",\"type\":\"string\"},{\"name\":\"Disabled\",\"type\":\"boolean\"}],\"name\":\"AlertRule\",\"namespace\":\"ddstatsprocessor.alerts\",\"type\":\"record\"}"
}

func (r *AlertRule) Serialize(w io.Writer) error {
	return writeAlertRule(r, w)
}
