// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     statspoint.avsc
 */

package kafka

import (
	"io"
)

type StatsPoint struct {
	Start          int64
	Duration       int64
	Measure        string
	Submeasure     string
	Value          float64
	DomainID       string
	NodeUUID       string
	Service        string
	Operation      string
	Env            string
	HTTPStatusCode string
}

func DeserializeStatsPoint(r io.Reader) (*StatsPoint, error) {
	return readStatsPoint(r)
}

func NewStatsPoint() *StatsPoint {
	v := &StatsPoint{}

	return v
}

func (r *StatsPoint) Schema() string {
	return "{\"fields\":[{\"name\":\"Start\",\"type\":\"long\"},{\"name\":\"Duration\",\"type\":\"long\"},{\"name\":\"Measure\",\"type\":\"string\"},{\"name\":\"Submeasure\",\"type\":\"string\"},{\"name\":\"Value\",\"type\":\"double\"},{\"name\":\"DomainID\",\"type\":\"string\"},{\"name\":\"NodeUUID\",\"type\":\"string\"},{\"name\":\"Service\",\"type\":\"string\"},{\"name\":\"Operation\",\"type\":\"string\"},{\"name\":\"Env\",\"type\":\"string\"},{\"name\":\"HTTPStatusCode\",\"type\":\"string\"}],\"name\":\"StatsPoint\",\"namespace\":\"ddstatsprocessor\",\"type\":\"record\"}"
}

func (r *StatsPoint) Serialize(w io.Writer) error {
	return writeStatsPoint(r, w)
}
